### ISSUE TITLE
Online vs Offline Questions

### ISSUE THREAD

**Issue by burrrata** [Mrtenz/FindETH#179]
Watching this load and it installed PhantomJS. From the website I'm assuming that this and the `server` package is to fetch the token balances online? 
- would it be possible to sync to a local node instead?
- would it be possible to have the scripts run to determine all the possible addresses, then let user fetch the token balances on their own?
(not sure how much of a pain in the ass these might be so I'm actually asking)

**Comment by Mrtenz** [comment]
> From the website I'm assuming that this and the `server` package is to fetch the token balances online?

Not quite. The server package is used by the desktop application (built with Electron), to communicate with hardware wallets. The server will automatically be run locally (and not exposed to the internet, of course!) when you start the desktop app, and with an HTTP-like communication protocol, data can be fetched from hardware wallets, through the native libraries. It's based on [this approach here](https://gist.github.com/wbobeirne/ec3e52b3db1359278c19f29e1bbfd5f1). This is still a work-in-progress feature, though.

> Would it be possible to sync to a local node instead?

Not yet. I am planning on adding a feature where you can choose from different nodes, including your own, and other EVM-like networks (Ethereum forks). Currently, everything is fetched mainly from MyCrypto's node, with fallbacks to Etherscan and Infura.

> Would it be possible to have the scripts run to determine all the possible addresses, then let user fetch the token balances on their own?

As in, some way to export the addresses without fetching balance for them? That's currently not possible. Is there a specific reason why you want this?

**Comment by burrrata** [comment]
Thanks for your detailed responses :)

and I was just curious if the offline address lookup => online fetch was possible, more as a way to reduce any potential security holes than anything (it's not a great idea, but I was just curious if it was possible)

**Comment by Mrtenz** [comment]
No sensitive data is ever sent to the server, only your addresses. When support for custom nodes is added, you're free to use your own node, to reduce any potential security risks. Unfortunately, I don't have a timeline for this yet.

I think I can close this issue for now. Feel free to open another issue, if you have more questions, feature suggestions or anything else!
