### ISSUE TITLE
unlock account

### ISSUE THREAD

**Issue by zeezee54** [Mrtenz/FindETH#253]
unable to unlock mnemonic option only available locally message

**Comment by Mrtenz** [comment]
For security reasons, you can only use a local version of FindETH to unlock with a mnemonic phrase. Either use the instructions found in the README.md, or download a local version from here: https://github.com/Mrtenz/FindETH/releases/tag/v1.1.2 (FindETH.zip).

**Comment by zeezee54** [comment]
local version not working

________________________________
